spring:
  application:
    name: addition-service
  freemaker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/addition-server/templates/
error:
  path: /error
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'